### ISSUE TITLE
Case insensitive file search on OS X

### ISSUE THREAD

**Issue by BuXY** [trol73/trol-commander-dist#3]
Hi there,

tried to search for files *user* on OS X, and it did not find a file whose name was containing the string User. I know, *nix is a very case sensitive system, but though, it would be nice to have a case insensitive file search in this great tool.

Thanks!

p.s. In the menu bar the About window menu item says About Launcher :)

**Comment by trol73** [comment]
A good point about case insensitive search, Thanks!

Regarding 'About Launcher' - thats already fixed, use nightly build from google drive :)

**Comment by trol73** [comment]
Version 0.9.6 released
