### ISSUE TITLE
Start Splash screen and window title still say "muCommander"

### ISSUE THREAD

**Issue by transistorgrab** [trol73/trol-commander-dist#4]
Hi,

just wanted to point out that though the main program name was changed these things still have the same name as the original.
Also I would suggest to change the program icon, even a small change (for example just the color) would make it easier to differentiate between the two programs.
Thanks for the fork, I really loved muCommander. :)

Best regards.

**Comment by trol73** [comment]
Hi,

unfortunately I have not enough designers skill to modify graphics. And now my primary goal is new features and bugfixes.
But maybe someday someone draws the new graphics for trolCommander :)

**Comment by transistorgrab** [comment]
I would volunteer to provide a suggestion but where is the repository where the development is done?

**Comment by trol73** [comment]
The source repository is here http://github.com/trol73/mucommander (see develop branch)

**Comment by transistorgrab** [comment]
Made my suggestion, sent pull request. Hope it helps and finds your approval. If not, I'm open for improvements. :)

**Comment by trol73** [comment]
Thanks a lot! Now trolCommander will have a new image :)
